### ISSUE TITLE
RuntimeError: The size of tensor a (48) must match the size of tensor b (24) at non-singleton dimension 0

### ISSUE THREAD

**Issue by dAItime001** [kijai/ComfyUI-ControlNeXt-SVD-Wrapper#10]
Starting server
To see the GUI go to: http://127.0.1.1:8189 or http://127.0.0.1:8189
To see the GUI go to: https://127.0.1.1:8190 or https://127.0.0.1:8190
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
got prompt
model weight dtype torch.float16, manual cast: None
model_type V_PREDICTION_EDM
Using pytorch attention in VAE
Using pytorch attention in VAE
model weight dtype torch.float16, manual cast: None
model_type V_PREDICTION_EDM
Requested to load CLIPVisionModelProjection
Loading 1 new model
loaded completely 0.0 1208.09814453125 True
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 186.42957878112793 True
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (61) greater than context_length 24.
Requested to load SVD_img2vid
Loading 1 new model
loaded completely 0.0 2907.987678527832 True
  0%|                                                                                                      | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! The size of tensor a (48) must match the size of tensor b (24) at non-singleton dimension 0
Traceback (most recent call last):
  File "/opt/data/LLM/ComfyUI_TTS/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/opt/data/LLM/ComfyUI_TTS/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/opt/data/LLM/ComfyUI_TTS/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/opt/data/LLM/ComfyUI_TTS/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/opt/data/LLM/ComfyUI_TTS/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/opt/data/LLM/ComfyUI_TTS/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 526, in motion_sample
    latents = orig_comfy_sample(model, noise, *args, **kwargs)
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "/opt/data/LLM/ComfyUI_TTS/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/opt/data/anaconda3/envs/ComfyUI-TTS/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/k_diffusion/sampling.py", line 144, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 635, in evolved_sampling_function
    cond_pred, uncond_pred = sliding_calc_conds_batch(model, [cond, uncond_], x, timestep, model_options)
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 887, in sliding_calc_conds_batch
    sub_conds_out = calc_conds_batch_wrapper(model, sub_conds, sub_x, sub_timestep, model_options)
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 993, in calc_conds_batch_wrapper
    return comfy.samplers.calc_cond_batch(model, conds, x_in, timestep, model_options)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/opt/data/anaconda3/envs/ComfyUI-TTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/data/anaconda3/envs/ComfyUI-TTS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/LLM/ComfyUI_TTS/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 868, in forward
    h = p(h, transformer_options)
  File "/opt/data/LLM/ComfyUI_TTS/custom_nodes/ComfyUI-ControlNeXt-SVD/nodes.py", line 534, in input_block_patch
    conditional_controls = (conditional_controls - mean_control) * (std_latents / (std_control + 1e-5)) + mean_latents
RuntimeError: The size of tensor a (48) must match the size of tensor b (24) at non-singleton dimension 0

Prompt executed in 35.18 seconds

Restarting... [Legacy Mode]

有没有遇到这个问题或相似问题，如何解决

**Comment by RONNYKHALIL** [comment]
+1

**Comment by nitinmukesh** [comment]
This kind of issue happens when the no of frames to be processed is less than FPS or both are equal.
OR
The width / height not divisible by 64.

I don't use Comfyui so can't confirm.

**Comment by h1shen** [comment]
+1

**Comment by speewer** [comment]
+1

**Comment by xusonlin** [comment]
I got the same error, who resovled this?
