### ISSUE TITLE
controlnext-svd_v2-unet-fp16_converted.safetensors--应该放在哪个位置？Where should the file be placed?

### ISSUE THREAD

**Issue by mingda27** [kijai/ComfyUI-ControlNeXt-SVD-Wrapper#8]
请问作者，diffusers版本的工作流成功运行了，原生版本的没能运行成功，提示Value not in list: unet_name: 'controlnext-svd_v2-unet-fp16_converted.safetensors' not in []，我不知道应该把这个文件放在哪里。

May I ask the author, the workflow of the diffusers version ran successfully, but the native version failed to run successfully, and the prompt "Value not in list: unet_name: 'controlnext-svd_v2-unet-fp16_converted.safetensors' not in []" was prompted. I don't know where I should put this file.
![image](https://github.com/user-attachments/assets/d2186f01-2d69-4196-9a9c-8c5327c27774)

**Comment by mingda27** [comment]
我知道了，放在ComfyUI/models/unet/里面

**Comment by FourTest** [comment]
我正常放置位置了,但是报错:
errors:
!!! Exception during processing!!! 'conv_in.weight'
Traceback (most recent call last):
  File "/data/test/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/test/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/test/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/test/ComfyUI/nodes.py", line 814, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "/data/test/ComfyUI/comfy/sd.py", line 603, in load_unet
    model = load_unet_state_dict(sd)
  File "/data/test/ComfyUI/comfy/sd.py", line 576, in load_unet_state_dict
    model_config = model_detection.model_config_from_diffusers_unet(sd)
  File "/data/test/ComfyUI/comfy/model_detection.py", line 380, in model_config_from_diffusers_unet
    unet_config = unet_config_from_diffusers_unet(state_dict)
  File "/data/test/ComfyUI/comfy/model_detection.py", line 262, in unet_config_from_diffusers_unet
    match["model_channels"] = state_dict["conv_in.weight"].shape[0]
KeyError: 'conv_in.weight'
