### ISSUE TITLE
UNETLoader  error

### ISSUE THREAD

**Issue by FourTest** [kijai/ComfyUI-ControlNeXt-SVD-Wrapper#9]
I downloaded **controlnext-svd_v2-unet-fp16_converted.safetensors** and placed it in the **ComfyUI/models/unet/** directory, but when running **controlnext_svd_comfy_01.json**, the node **UNETLoader** reported the following error:

![1234](https://github.com/user-attachments/assets/b84ef963-7508-45d2-a096-e32d6713a6d7)

!!! Exception during processing!!! 'conv_in.weight'
Traceback (most recent call last):
  File "/data/test/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/test/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/test/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/test/ComfyUI/nodes.py", line 814, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "/data/test/ComfyUI/comfy/sd.py", line 603, in load_unet
    model = load_unet_state_dict(sd)
  File "/data/test/ComfyUI/comfy/sd.py", line 576, in load_unet_state_dict
    model_config = model_detection.model_config_from_diffusers_unet(sd)
  File "/data/test/ComfyUI/comfy/model_detection.py", line 380, in model_config_from_diffusers_unet
    unet_config = unet_config_from_diffusers_unet(state_dict)
  File "/data/test/ComfyUI/comfy/model_detection.py", line 262, in unet_config_from_diffusers_unet
    match["model_channels"] = state_dict["conv_in.weight"].shape[0]
KeyError: 'conv_in.weight'

**Comment by kijai** [comment]
Your ComfyUI is out of date, the UNETLoader node has been replaced by Load Diffusion Model:

![image](https://github.com/user-attachments/assets/ca03b97a-f5f8-4d4d-be82-96bf6b12cf6b)

**Comment by FourTest** [comment]
Thanks.

**Comment by FourTest** [comment]
good job
